apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clear-jobs
  namespace: api
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: job-reader-sa
          containers:
          - name: clear-failed-jobs
            image: k8s_jobs_cleaner:latest
            imagePullPolicy: Never
            args:
            - python
            - clear_jobs.py
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CRONJOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          restartPolicy: OnFailure
